[workspace]
authors = ["Anand Balakrishnan <anandbala1597@gmail.com>"]
channels = ["conda-forge"]
platforms = ["linux-64"]
preview = ["pixi-build"]
exclude-newer = "30d"

[dependencies]
python = "3.12.*"

[pypi-dependencies]
logic-asts = { path = ".", editable = true }

[feature.test.dependencies]
pytest = "*"
pytest-mypy = "*"
pytest-timeout = "*"
hypothesis = "*"
spot = "*"

[feature.docs.dependencies]
myst-parser = "*"
sphinx = "*"

[feature.dev.dependencies]
basedpyright = "*"
ipython = "*"
rich = "*"
mypy = "*"
pyrefly = "*"
ruff = "*"
just = "*"
ty = "*"
zuban = "*"

[environments]
default = { features = ["dev", "test", "docs"], solve-group = "default" }

[package.build]
backend = { name = "pixi-build-python", version = "*" }

[package.build.config]
ignore-pypi-mapping = false
