name: "Test, build, and deploy Python package"

on:
  pull_request:
    branches: [main]
  create:
    tags:
      - v*
permissions:
  contents: read

jobs:
  test:
    name: Test package
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12", "3.13"]

    steps:
      # checkout@v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      # setup-uv@v6.0.1
      - uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca
        with:
          version: "latest"
          python-version: ${{ matrix.python-version }}
      - name: Test with Python ${{ matrix.python-version }}
        run: uv run --frozen --dev pytest
      - name: Run type checker with Python
        run: uv run --frozen --dev mypy src tests

  release-build:
    name: Build package
    runs-on: ubuntu-latest
    needs:
      - test

    steps:
      # checkout@v4.2.2
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
      # setup-uv@v6.0.1
      - uses: astral-sh/setup-uv@6b9c6063abd6010835644d4c2e1bef4cf5cd0fca
        with:
          version: "latest"
      - name: Install dependencies
        run: uv sync
      - name: Build wheels and sdist
        run: uv build
      - name: Upload wheels and sdist
        # upload-artifact@v4.6.2
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest

    needs:
      - release-build

    permissions:
      # IMPORTANT: this permission is mandatory for trusted publishing
      id-token: write

    # Dedicated environments with protections for publishing are strongly recommended.
    environment:
      name: pypi
      # OPTIONAL: uncomment and update to include your PyPI project URL in the deployment status:
      url: https://pypi.org/p/logic-asts

    steps:
      - name: Retrieve release distributions
        # download-artifact@v4.3.0
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        # gh-action-pypi-publish@v1.12.4
        uses: pypa/gh-action-pypi-publish@76f52bc884231f62b9a034ebfe128415bbaabdfc

